### ISSUE TITLE
Selection of multiValued form editor disappears upon scroll

### ISSUE THREAD

**Issue by RafaPolit** [KETSE/casebox#11]
## General description of issue
The problem occurs on a multiValued Object field with editor "Form" assigned to a thesauri Scope that contains several items (for instance countries) which require scrolling or paging.  After clicking on a value, if I scroll down, the selection is lost.

## Way to reproduce
- Create a thesauri folder named countries (for example)
- Create inside several items, in my case I have 44, I suspect at least 20 or so to see the issue
- Create a country object field inside a case or templates template with the following configuration (replacing scope with the actual #id):

```
{
  "scope": 99,
  "multiValued": true,
  "editor": "form",
  "renderer": "listGreenIcons"
}
```
- Create a case, click inside the countries input, a popup appears with the form
- Select the second country
- Scroll down to select the last country

At this point the first selection **gets unselected**, the show selection button is **greyed out** and if you click OK, there is no selection to be found.  Also, (but this is probably a separate bug/issue): the paging list is showing 1-25 of 44 (in my case) but I can see all 44 if I scroll.

## Tested in
- I have tried this only on Chrome, perhaps other browsers are not showing the issue?

Hope this helps, thanks
Rafa.

**Comment by tvitalie** [comment]
Hi Rafa, 
thank you very much for all the work you do on Casebox.

I tried to reproduce current issue and cant find the bug.
Similar result can be obtained only for single valued field, so I would like to ask you to double check it.

Check field config,  if no errors in param names.

Note: After changing a field config the browser should be reloaded to have templates structure updated on client side.

**Comment by oburlaca** [comment]
@RafaPolit, I confirm that the list is showing all results and not the first 25, this is a bug.
I've tried "select 2nd country ... select last scenario", I don't have the issue you have. you can send us the SQL dump so we have the exact data/configs to check.

**Comment by RafaPolit** [comment]
I believe this has been confirmed as a bug, I would like this reopened.

Thanks.

**Comment by oburlaca** [comment]
@tvitalie edit item #6911 in our dev instance, field countries. click the field to edit it, when the form appears, use mouse and drag the scrollbar of the list, all 3 selected items are deselected

**Comment by tvitalie** [comment]
I see now, I was using the mouse wheel to scroll and didn't catch this bug.
It appears when clicking on scrollbar or when clicking in grid container (not on a row).
Will be fixed with next commit.

**Comment by tvitalie** [comment]
@RafaPolit, issue fixed in last commit.
Please check and confirm if ok.

Best regards

**Comment by RafaPolit** [comment]
I confirm its working as expected on the last commit.  Thanks!
