### ISSUE TITLE
Object Permissions - User Labels disappearing after update

### ISSUE THREAD

**Issue by lolziac** [KETSE/casebox#18]
Dealing with Object Permissions, when you add/assign Users and configure the Permissions attributes everything seems/shows fine, until you save/update the object record.
If you reopen the Permissions window again you can see that User Labels disappear and you don't know which user has what rights !!!
This is happening only for Users, for Groups they work fine.

See Image:
![user-label-object-permissions](https://cloud.githubusercontent.com/assets/583004/9079880/f2c6b1c4-3b4e-11e5-9d22-54a3de5d0d5c.png)

Regards,
lolziac

**Comment by tvitalie** [comment]
Fixed in last commit, please ckeck.

**Comment by lolziac** [comment]
Perfect tvitalie,

I just test it and I can confirm this issue as fixed. :)

**Comment by testingbykumar** [comment]
Hi CB Team,

I am new. I learned to create case,Events and tasks. I have given permission to users to create task,case and event. It is not working as expected. Could you please help me to fix it.

![casebox demo](https://cloud.githubusercontent.com/assets/15153647/10535818/a75a2ba6-7403-11e5-8350-71fde344d043.png)

My goal is to, admin only can access system folder and other users can create their own case, events  and task who Admin give permission.
