### ISSUE TITLE
"New" button has disappeared from new dev version on all folders

### ISSUE THREAD

**Issue by RafaPolit** [KETSE/casebox#21]
## Basic description
We pulled the latest devel version that fixes several bugs we have reported in recent days, but now the 'new' button has disappeared.  We cannot create new thesauri items, nor add new cases to our casebox core using the UI.

** edit: ** If this is a clue, there is a new 'lock' button next to the folder where we created the cases, also the 'new' button is missing from everywhere... cannot even create a new folder inside the 'All folders' section.

What could have changed? Permissions? Folder owners?

Thanks,
Rafa.

**Comment by tvitalie** [comment]
The menu model has changed, we have mentioned the changes in change log.
These are the notes form changelog CaseBox 1.9.496 (2015-07-24): 

Notes:
----------
- /bin/core_update_menu_model.php should be executed to upgrade menu mode for existent cores
  (php core_update_menu_model.php -c <core_name>)
  script will remove menu table for DB transfering all rules in tree in System/Menus folder

**Comment by RafaPolit** [comment]
Thanks.  Still not working, as executing that script yields a warning of header modification:

´´´
Initializing .. 
____________________________
preparing target DB: 
Ok

Initializing target core ..PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/casebox/httpsdocs/classes/CB/Import/Base.php:208) in /var/www/html/casebox/httpsdocs/config.php on line 34
´´´

**Comment by tvitalie** [comment]
In my previous comment the core_name was removed from command to be executed because interpreted as a tag.
You can read executing notes inside script as well.
Command should be something like this 
php core_update_menu_model.php -c "my_core_name"

my_core_name is without standart prefix (specified in config.ini)

**Comment by RafaPolit** [comment]
Yep, I edited my comment... still, entering a **wrong** core name results in a PHP error.  Otherwise, the script worked nicely, and nice to see menus can now be edited inside the casebox UI instead of directly on the db.

Thanks,
Rafa.

**Comment by nouphaltklm** [comment]
I am also facing the same issue. I couldn't find the "core_update_menu_model.php" inside bin folder. What should i do? any help would have been really nice..

**Comment by tvitalie** [comment]
I suppose you already have installed casebox v2, this issue was in v1.
The menu are now managed from tree: System/Menu folder.

If the problem persists - add more info about your installation and add some screenshots.
