### ISSUE TITLE
PreviewExtractor with a snake case core name does not work.

### ISSUE THREAD

**Issue by daneryl** [KETSE/casebox#23]
With a core name like "my_core" PreviewExtracor init function splits by "_" the core name to configure the server with the last item of the split like "**core**.dummy.com", this is used in posterior process to detect the core name by the detect_core() function, after this the core name used by casebox is "core" instead of "my_core" and all the preview generation will fail without any error.

I solved this changing all my core names to camel case, really easy to solve, but it was very hard to debug, a fix or a warning on this i think is needed.

**Comment by tvitalie** [comment]
I will exclude that explode by "_" in next commit to prevent other people from having same issue.
Thanks for reporting it.
Best regards.
