### ISSUE TITLE
Creating new folder templates to show different columns

### ISSUE THREAD

**Issue by RafaPolit** [KETSE/casebox#24]
## General need
I want to create a new 'folder' type of template (lets call it a **case_folder** template) in order to show inside records with specific columns configured. This is working as expected with the DC property.  The problem is that this 'case-folder' type of template does not get shown as a subfolder of the parent folder.

I want to create several 'case-folders' inside, say a folder called Cases, but I want the child folders to be shown correctly on the tree view.  I want to click on the arrow (which is not there if the case folder only contains case-folders inside) and see the folders in the tree.

Just like the dev casebox shows the project folders inside the tasks, for example.

Is there a basic config I am missing in order to enable this on the parent folder?

Thanks in advance for any feedback, its kind of hard to explain what I need, so if further details are needed I'm more than happy to explain as detailed as needed.

Thanks, best regards,
Rafa.

**Comment by oburlaca** [comment]
see https://www.casebox.org/dev/docs/server-architecture/ and http://www.casebox.org/dev/docs/tree/

You need to specify the ID of the case_folder template in the **folder_templates** config in mysql table.

P.S. Thanks for such detailed explanation of the use case, it gives us ideas how to make CB more flexible. In this particular situation the solution already existed though )
