### ISSUE TITLE
User permission 

### ISSUE THREAD

**Issue by testingbykumar** [KETSE/casebox#25]
I am new. I learned to create case,Events and tasks. I have given permission to users to create task,case and event. It is not working as expected. Could you please help me to fix it.

![casebox demo](https://cloud.githubusercontent.com/assets/15153647/10538582/16ff8628-7417-11e5-8bde-e00767af1cec.png)

My goal is to, admin only can access system folder and other users can create their own case, events and task who Admin give permission.

**Comment by tvitalie** [comment]
Hi @testingbykumar.
By default "System" folder is accessible only for root user.
Only root can edit permissions for that folder and change them.

From screenshot I see you are trying to set security for task template which will affect the right to change the template itself but not the items created from that template.

You shouldn't set permissions to any child/subchild items of "Sistem" folder.

Take a look at  "System/Menus" folder. 
There you can define Menu items available to be created per folders and/or per user.

**Comment by testingbykumar** [comment]
Thank you Tvitalie. You mean by giving permission to menu. User can able to create case / folder and event also how to enable Calendar options ?

Thanks in advance !

**Comment by tvitalie** [comment]
Sorry, I mean to create corresponding rules in that folder to allow specific users create specific items in specific folders.

**Comment by testingbykumar** [comment]
Tvitalie@thank you. I have given permission to user and a group but not able to create folder,case and events. Let me know to handle this. Attached screenshot.
![casebox demo](https://cloud.githubusercontent.com/assets/15153647/10605288/e1c4a694-7747-11e5-9fa2-394d2ac36f4c.png)

My goal is to I will assign few user to create case, event and folder based on permission. 
Thank you again.

**Comment by tvitalie** [comment]
Once you've created such rule you have to login with one of those users, for which you created it, and when you browse the folders (lets say select folder "abu001" from tree) then you have to check the items available for creation in "New" menu from grid toolbar or left ribbon.

**Comment by testingbykumar** [comment]
I agree but when I login with the same user and created a case , folder or event. It is showing access denied  Is there anything wrong in node id or template ID 

![cb](https://cloud.githubusercontent.com/assets/15153647/10617295/59353542-7787-11e5-87e5-aa401bfaace7.PNG)

Could you please share ur email ID ?

**Comment by tvitalie** [comment]
Its because the user doesn't have access to create items in target
directory.
As I see from screenshot its "Tree".

On Tue, Oct 20, 2015 at 9:35 PM, testingbykumar <notifications@github.com>
wrote:

> I agree but when I login with the same user and created a case , folder or
> event. It is showing access denied Is there anything wrong in node id or
> template ID
>
> [image: cb]
> <https://cloud.githubusercontent.com/assets/15153647/10617295/59353542-7787-11e5-87e5-aa401bfaace7.PNG>
>
> Could you please share ur email ID ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KETSE/casebox/issues/25#issuecomment-149659139>.
>



-- 
Respectfully,
Țurcanu Vitalie Alexandru.

**Comment by testingbykumar** [comment]
Could you please help me with screenshot. I am sorry to trouble you again.

**Comment by testingbykumar** [comment]
Hi Țurcanu,

Thank you so much for your kind help.
*My next challenge tasks*

I want to create and download case/ tasks and assigned user base on
template inputs.
*how to create export for each case and assigned users ?*

*Input using casebox*




*​*
*Output in Excel format*


​
