### ISSUE TITLE
Template load error: no template found with id =x

### ISSUE THREAD

**Issue by testingbykumar** [KETSE/casebox#27]
I am getting error as Template load error: no template found with id =x
X is Properties ID. When I click Thesauri field and edit. Error showing. Unable to create auto generated folder.
Help me in this..

**Comment by testingbykumar** [comment]
![4 casebox demo](https://cloud.githubusercontent.com/assets/15153647/10838936/572b4822-7ef3-11e5-890b-382fe3bd4b68.png)
Here is the screen shot for better understanding.

**Comment by tvitalie** [comment]
The bug that were causing such situation was fixed in previous commits.
Now the "Template load error" shouldn't appear.
