### ISSUE TITLE
Trying to install on Ubuntu 14.04 issues..

### ISSUE THREAD

**Issue by idistech** [KETSE/casebox#28]
Hi, Im trying to get Casebox installed and evaluated on a Ubuntu 14.04 system.

We have had some permission issues, and have re-installed Solr as www-data user, so now there are no problems sharing files between apache/Casebox...

i) We would like to run the install.php script and create a workbench ( lets say 'test' ) from the command line, I can see that the scripts have some Non-interactive but can see how to run the install to create the links to Solr, the cb__casebox db, and then the cb_test database & links from the command line - has any box managed to do this ?

ii) The database seems to create a user with a 'recovery email address' of 'adminΩmail.server.com' is there anyway of setting this during installation.

Many thanks for you help.

Gary

**Comment by idistech** [comment]
Update ..
Im also having problems installing the database, with two errors.. is this being seen by anyone else ?

# php bin/install.php 
Specify apache user (default "www-data"):

Specify prefix used for database names, solr core and log files (default "cb"):

Specify database configuration:
db host (default "127.0.0.1"): 
db port (default "3306"): 
db user (default "casebox"): 
db password: *********
privileged db user (default "root"): 
privileged db user's password:************
Provide server name with protocol (default "*******************************/"):

solr aucreate cores ?Y

Specify solr configuration:
solr home directory (default "/var/solr/data/"): 
solr host (default "127.0.0.1"): 
solr port (default "8983"): 
Specify administrator email address (default "admin@*****************"):

Specify sender email address, placed in header for sent mails (default "webmaster@*********************"):

Would you like to define comments email parametters [Y/n]: n
Specify python path (default "python"):

Specify backup directory (default "/var/www/html/casebox/backup/"):


You have configured main options for casebox.
Saving your settings to /var/www/html/casebox/httpsdocs/config.iniOK
Solr configsets symlinks created sucessfully.
Solr core cb__log exists or can't access solr. Would you like to try to create it [Y/n]: Y
Unloading core log... OK
Creating solr core ... OK
create Main Database:
cb__casebox database does not exist. Would you like to create it from current installation dump file [Y/n]: Y
Create database cb__casebox
**ERROR 1054 (42S22) at line 198: Unknown column 'udate' in 'NEW'**

Casebox was successfully configured on your system
you should create at least one Core to use it.
Do you want to create a basic default core [Y,n]: Y
Core name:
test
**ERROR 1054 (42S22) at line 744: Unknown column 'udate' in 'NEW'**
OK
Registering core .. OK
Specify email address for root user:
********************
Specify root user password:
**********
Specify default language (ISO) (default "en"):

UI available languages (comma separated ISO list) (default "en"): 

Solr core already exists, overwrite [Y/n]: Y
Unloading core test... OK
Creating solr core ... OK
Reindex core [Y/n]: Y
Reindexing core ... 
2015-11-07 17:52:32 Processing core test ... updating tree
optimizing
OK
Creating language files .. OK
Done.
Done




many thanks

**Comment by kikihakiem** [comment]
I already follow all the instructions on setting it up in Ubuntu 14.04.
I only having an issue when running `bin/install.php`:
`Unknown column 'udate' in 'NEW'` 

When I try to access http://casebox.local/ or http://127.0.0.1/ I get HTTP error 403. 
Please help

**Comment by tvitalie** [comment]
Hi idistech and kikihakiem,
I've updated sqls used for install on master branch.

Please try again and see if it works ok for you.

**Comment by idistech** [comment]
Will do, thanks..

**Comment by idistech** [comment]
Still there 

Applying dump .. ERROR 1054 (42S22) at line 198: Unknown column 'udate' in 'NEW'
&
ERROR 1054 (42S22) at line 744: Unknown column 'udate' in 'NEW'

**Comment by tvitalie** [comment]
did you make git pull again ?

**Comment by tvitalie** [comment]
This also refers to cb__casebox, better drop these databases if you can ant run install again.
Or you can run the following sql in both databases: 
DROP TRIGGER IF EXISTS `translation_bu`;

**Comment by idistech** [comment]
OKay, my mistake, after doing a fresh pull , and not a master extract, I got the right file.
*.sql now loads... got another error, but ill try and work on that, seems the db is now loaded .
thanks
