### ISSUE TITLE
unable to install casebox

### ISSUE THREAD

**Issue by basemh** [KETSE/casebox#30]
I followed all the instructions but this is what I get when I run install script:

cd /var/www/htm/casebox
php bin/install.php

You have configured main options for casebox.
Saving your settings to /var/www/html/casebox/httpsdocs/config.iniOK
Solr configsets symlinks created sucessfully.
PHP Notice:  Undefined index: SOLR_CLIENT in /var/www/html/casebox/httpsdocs/lib/install_functions.php on line 281
PHP Warning:  require_once(/var/www/html/casebox/httpsdocs/libx): failed to open stream: No such file or directory in /var/www/html/casebox/httpsdocs/classes/CB/Solr/Service.php on line 87
PHP Fatal error:  require_once(): Failed opening required '' (include_path='/var/www/html/casebox/httpsdocs/libx:/var/www/html/casebox/httpsdocs/libx/min/lib:/var/www/html/casebox/httpsdocs/libx/ZF/library/:/var/www/html/casebox/httpsdocs/classes:/var/www/html/casebox/httpsdocs/plugins/:.:/usr/share/php:/usr/share/pear') in /var/www/html/casebox/httpsdocs/classes/CB/Solr/Service.php on line 87
root@casebox:/var/www/html/casebox# vim /var/www/html/casebox/httpsdocs/lib/install_functions.php

**Comment by pcmerc** [comment]
I'm not sure if it's intentional or not but it's sad when open source projects have broken code as to drive you to contact their support in setup. 

correct install_functions.php by adding         ,'SOLR_CLIENT' => \CB\DOC_ROOT . 'libx/Apache/Solr/Service.php' to the getDefaultConfigValues function at the top of the file

**Comment by pcmerc** [comment]
Another thing, does this require: 
curl -sS https://getcomposer.org/installer | php
php composer.phar install

As that is not mentioned in any of the docs if so but there is a composer.json so I assume so.

**Comment by basemh** [comment]
Thanks for Help, however I am not a developer and I have very basic programming skills that would help me to amend your fix code, but I am still worry to use CaseBox, I moved to OwnCloud, it does satisfy my needs.

**Comment by nfsecurity** [comment]
The same problem here. 
Thank you pcmerc for your comments.

**Comment by JOH451** [comment]
Tried to install this a few days ago and had exactly the same problem. pcmerc's suggestion overcame the initial problem with SOLR_CLIENT being undefined but now have other problems with install.php which I need to look into.

**Comment by thanhchatvn** [comment]
Hi, i the same error, how to fix it ? Please

**Comment by tvitalie** [comment]
Hi guys, sorry for delayed answer.
I'm preparing next commit that will fix this issue.

Best regards.

**Comment by tvitalie** [comment]
I've made the commit on devel branch,
You can pull that branch and try to install Casebox while we merge into master.

**Comment by thanhchatvn** [comment]
@tvitalie : i pull and this bug is fixed, thanks you so much, you is pro (y)

**Comment by tvitalie** [comment]
This issue is fixed and merged into master branch.
