### ISSUE TITLE
Uploading not finishing

### ISSUE THREAD

**Issue by pablocerdeira** [KETSE/casebox#33]
Version: devel brunch from 17 december 2015.

I'm trying to upload files, but the first one does not get finished.

I can see 2 file on my upload queue. 
First file: size: 1.7 MB; status: uploading; percent: 100%
Second file: size: 1.4 MB; status: ; percent: 

Although the first file does not appear as completed, but uploading, I can see it on my upload folder and even its content on the side panel. But as it still appears as uploading, the second one does not start to upload.

The error I can find on my error log is (but I'm not sure if this error is related to the error described above):
PHP Fatal error:  Call to undefined function CB\Solr\curl_init() in /var/www/html/casebox/httpsdocs/classes/CB/Solr/Service.php on line 197

**Comment by tvitalie** [comment]
It seems that you don't have curl installed, or activated in php.ini, for you php instance.

**Comment by pablocerdeira** [comment]
Perfect! All fine now. 
I'd suggest to add "sudo apt-get install php5-curl" on the "Revised instructions for Ubuntu 14.04 Clean Install": https://github.com/KETSE/casebox/issues/9

Thanks so much,
