### ISSUE TITLE
How to Install Casebox

### ISSUE THREAD

**Issue by irsadmin** [KETSE/casebox#37]
Hey world.

Is anybody can define Casebox easy installation tutorial on new organization? In Windows or Linux base server?

**Comment by tvitalie** [comment]
https://www.casebox.org/dev/install/

**Comment by irsadmin** [comment]
i have tried this links, and gone all setup by setup but couldn't configure my server. i have also tried these setups on virtual machine https://github.com/KETSE/casebox/wiki/How-to-install-Casebox-on-a-fresh-Ubuntu-14.04 but not able to enjoy Casebox. please help me or give me any expert email id, how can resolve my problem.

**Comment by irsadmin** [comment]
I want to configure a local are network Casebox server, please share video tutorial of installation, setup by setup and detailed.

**Comment by oburlaca** [comment]
Hello irsadmin,
Thanks for the hint to make a full video, we'll add it to our todo. At this
moment I'd suggest you find a developer that can help you with the setup.
We need detailed info from your error logs to see what is not ok on your
server

**Comment by wperdomos** [comment]
Hello, can someone please point me to the latest install documentation. Thanks

**Comment by vmelnic** [comment]
Hi @wperdomos try this one https://docs.google.com/document/d/15qvGi9tDHHHCItlCpbBB5fBnU5uhEpJedD5xudKVwPo/edit 
Also take a look to Casebox in vagrant (virtualbox) https://github.com/KETSE/casebox-vagrant

**Comment by vmelnic** [comment]
Setup documentation moved to https://github.com/KETSE/casebox/wiki
