### ISSUE TITLE
2 Step Authentication not working after git pull

### ISSUE THREAD

**Issue by nfsecurity** [KETSE/casebox#38]
Hello KETSE Team:

I did a "git pull" over the /var/www/casebox directory in order to update the software and have the latest bug-fixes. Then, I tried to login with my user, password and Google Authenticator app and surprise: Casebox is showing: wrong code entered.

I did some troubleshooting and I removed the "TSV" field in the table users_groups in database. With that, was possible to login, but the 2 Step Verification option in my account is failing to verify the code in the setup procedure with the same error: wrong code entered.

Can you review that ?, thank you so much. 

Best regards,

Julián Rios, CEO, CISSP/CFE

**Comment by tvitalie** [comment]
@nfsecurity I tested with Google Authenticator and had no problems.
Please make sure the time on your server doesn't have any shift, sync it with time servers.

**Comment by nfsecurity** [comment]
Thank you so much. That was the problem. I solve it in Centos 7 with:

# yum install ntp
# ntpdate -u 0.centos.pool.ntp.org
# systemctl start ntpd
# systemctl enable ntpd
