### ISSUE TITLE
Casebox VM demo password

### ISSUE THREAD

**Issue by sebbie42** [KETSE/casebox#39]
Hi guys, I am in the process of evaluating your CMS platform but am unable to login through the web interface. CentOS 6 VMware image.

Tried multiple user name / password combinations:
root / casebox
test / test
admin / casebox
test / casebox

Please help.
Rgds, Seb

![login bug](https://cloud.githubusercontent.com/assets/16265752/12575433/fb9006ba-c43e-11e5-93ab-672deb4ff9ba.jpg)

**Comment by tvitalie** [comment]
Hi @sebbie42, 
try root / demo

**Comment by sebbie42** [comment]
no luck with that combination either.. my web domain name is set to casebox and when I type in https://casebox on the host browser I am getting Apache 2 Test Page, https://casebox/demo gives me the login page. The only modifications I've made to client VM were to do with static ip / domain name settings.

**Comment by sebbie42** [comment]
.. update .. I have switched to Firefox browser and root / casebox login worked.
Native MS Edge on Windows 10 does not accept these credentials ( kicks back to login screen ).
