### ISSUE TITLE
Stuck at specify database config during install.php

### ISSUE THREAD

**Issue by mmcduffie1** [KETSE/casebox#40]
Followed the guide here https://github.com/KETSE/casebox/issues/9
When I run the install.php script it asked for a database config, then a privileged user then repeats this over and over with no end. See example below:

Specify database configuration:
db host (default "127.0.0.1"):
db port (default "3306"):
db user (default "local"): root
db password: *********************
privileged db user (default "root"):
privileged db user's password: *********************
Specify database configuration:
db host (default "127.0.0.1"):
db port (default "3306"):
db user (default "root"):
db password: *********************
privileged db user (default "root"):
privileged db user's password: *********************
Specify database configuration:
db host (default "127.0.0.1"): 127.0.0.1
db port (default "3306"): 3306
db user (default "root"): root
db password: *********************
privileged db user (default "root"): root
privileged db user's password: *********************
Specify database configuration:
db host (default "127.0.0.1"):

I copied and pasted that from my terminal. What am I doing wrong?

**Comment by tvitalie** [comment]
hi @mmcduffie1, 
It repeats because given credentials doesn't seem to be valid.
Install script checks the connection and if it fails it asks the connection params again.

Just try to connect to mysql from shell and see if you can connect:
mysql --user=root --host=127.0.0.1 -p

**Comment by mmcduffie1** [comment]
I can connect to the db. I changed the user and added a passwd just for casebox. After that I was able to get past this loop. However, now it fails to create the db. I think the issue is on my end. I'll update once I confirm in case the problem is not on me.

**Comment by wilo1** [comment]
Did you ever get a resolution to this situation? I am stuck at that same exact spot with it looping and looping!

**Comment by tvitalie** [comment]
Ok, you have to check also the host of the specified user.
There might be in mysql that user is allowed to connect only from localhost but on Casebox install you let it by default 127.0.0.1.

So, if you are sure your user and password is right, you can simply try to change db host to "localhost" instead of "127.0.0.1".

**Comment by mmcduffie1** [comment]
To update: I never found a solution to that issue. There are a whole host of new issues now. It seems things are no longer relative and absolute. I had to change a lot of code and filenames to get anything to work. There are calls for files that do not exist or misspelled names. I really wanted this project to work. The theory is perfect for my needs, however, implementing it now with the current instructions and no real structure have made it impossible. Please start answering issues and answer with more than v2 is coming and we'll update you then; then never updating.

**Comment by tvitalie** [comment]
Hi @mmcduffie1, dont know if you have noticed but the casebox have been updated and now there is v2 on master branch.
But anyway the most easy way that was created and is recommended for use is vagrant version, it is designed to be strait forward to get started: https://github.com/KETSE/casebox-vagrant
Best regards.

**Comment by mmcduffie1** [comment]
I am aware of the changes. Vagrant won't work in our environment. It is limited to such an extent that it would require more than we are willing to put into it. Just because it is allegedly a click and up does not mean it is actually a good way to run anything. The original direction this project was headed was perfect for almost anyone that needs Casebox. It's unclear why you abandoned that track. I would love to see the old version of Casebox working in the field. I think you guys have done a great job putting together something that just isn't out there. It's on my watchlist and I'll give it another go in 6 or 8 months.
