### ISSUE TITLE
Error redirect link after install Casebox on Ubuntu 14.04

### ISSUE THREAD

**Issue by kastowo** [KETSE/casebox#44]
Hi teams,

I have a problem about redirect link after installing the Casebox on Ubuntu 14.04. 
My url for localhost : "casebox.local/demo", after I submit the url redirect to "casebox.local/demo/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/casebox.local/demo/login/"

How to fix about it?
Thanks for your help,

Danang Kastowo

**Comment by tvitalie** [comment]
Hi kastowo,
I couldn't figure out how did you get such issue.
Tried different configs and changing host name but couldn't reproduce.
Suppose it's related to apache configuration.
