### ISSUE TITLE
install.php missing from GIT clone

### ISSUE THREAD

**Issue by lenjet** [KETSE/casebox#46]
cloned the master from GIT to do an install and the install.php file is missing in the /bin folder. 

I checked the master on GIT and it is missing there too?

**Comment by lenjet** [comment]
Sorry meant to say "I checked historical versions of master /bin folder"

**Comment by tvitalie** [comment]
Master branch was transferred into v1 branch.
Now in master is a new version that recommends using vagrant, check readme.
