### ISSUE TITLE
How Do I Install Casebox?

### ISSUE THREAD

**Issue by LudwigTirazona** [KETSE/casebox#55]
Basically, I'm following the install instructions at https://www.casebox.org/dev/install/
But the code that I clone doesn't even have a bin/install.php file.

Are there updated installation instructions somewhere that I don't know about?

Any help would be greatly appreciated! Thanks!

**Comment by tvitalie** [comment]
Hi, check https://github.com/KETSE/casebox/issues/50

**Comment by LudwigTirazona** [comment]
Thanks.
