### ISSUE TITLE
References from users?

### ISSUE THREAD

**Issue by Abraka** [KETSE/casebox#62]
Is there anybody, who had sucessfull implementaion of casebox? Judging local issues and responses from developers its looks like 1-2 man show, which scare me a little.
Whats about reliability, stability a scalability? How many documents-events can handle this project?
Did somebody try create new forms? For what exactly are you using casebox and how big is your installation?

**Comment by StuartIanNaylor** [comment]
Dunno but about to employ it in an advocacy centre.
I was going down the CiviCrm route but decided it was overly complex and had too much confusing bloat.
My next port of call was owncloud and the dev work to tweak that for purpose, then by chance came across casebox.
Its opensource and probably the perfect fit for client requirements and I will let you know how we get on.

**Comment by Abraka** [comment]
Thx, for info. I was looking for somebody, who run this thing at least for year and for 50-100+ heavy users. No reaction is also reaction, so lack of any reaction here...its speak forself.
Im already moved to SuiteCRM, which has everything I need and its highly customizable, so its possible to deactivate unneeded feauters. So far Im satisfied with it. 

Anyway good luck with casebox.

**Comment by whyfrycek** [comment]
Hello, yes, we have some ten implementations of Casebox running succesfully and for more than a year, in most cases for more than two years. Out of these, two fit the description of the organisation you are seeking to implement it for and so far everything is running fine.

In any case, I see you have moved to SuiteCRM and it seems to work well for you, so I guess it is too late. Sorry for the delayed response, many of us have taken an extensive break over the holidays and have not been as available as usual.
