### ISSUE TITLE
Faulty URL on email notifications

### ISSUE THREAD

**Issue by xelawafs** [KETSE/casebox#67]
I have installed casebox following the [Ubuntu-14.04-x64](https://github.com/KETSE/casebox/wiki/Ubuntu-14.04-x64) installatoin docs with [Apache2 Configuration](https://github.com/KETSE/casebox/wiki/Apache2-configuration).

I'm able to successfully login using the admin account on the browser. On creating a new user, an email notification is sent out for the user to complete registration. However, I notice the emails sent have a faulty URL missing a **forward slash before the c** at the end of the domain name as illustrated below:

```
http://casebox.example.comc/default/recover/reset-password?token=$2y$15$H9lrMaXFx4Bd9kGdjB1E0OLthbn76Tybu7M9tDakuh7iSK0.0w7M.e
```

**Comment by vmelnic** [comment]
Hi @xelawafs 
As quick fix. Try to update in 'app/config/default/parameters.yml' file, 'server_name' field value and add '/' - slash, at the end of your url.

Cheers!

server_name

**Comment by xelawafs** [comment]
Thanks for the hint @vmelnic Adding the slash on the `app/config/default/parameters.yml` file alone though doesn't do it. I had to run `composer update` again and fill the `server_name` prompt with the forward slash this time round. The email URL's now appears OK
