### ISSUE TITLE
Upgrading Casebox v1 to v2?

### ISSUE THREAD

**Issue by imadeter16** [KETSE/casebox#69]
Is there any guide to help upgrade a v1 installation and data to v2?

I was able to convert a running VM v1 example to suit our needs but the FILES are not stored in the same way as in v2.

The required conversion is just for the example setup. No data is required other than the setup itself (cases, offices, users/managers modifications, solr schema...)

Cheers

**Comment by imadeter16** [comment]
bump!

**Comment by vmelnic** [comment]
Hi @imadeter16,
As I know, the database structure differs from v1 to v2 version. I am sorry, but I can not help you.

**Comment by oburlaca** [comment]
v1 branch is used in production nowadays.
v2 branch (that has been moved to master) didn't reach the official release
and unfortunately there are no upgrade scripts

**Comment by imadeter16** [comment]
Thank you @vmelnic and @oburlaca for your responses. We will now concentrate on moving this v1 we're testing to prod soon. Very happy with it so far.
