### ISSUE TITLE
Revised instructions for Ubuntu 14.04 Clean Install

### ISSUE THREAD

**Issue by RafaPolit** [KETSE/casebox#9]
Thanks for all the great work!

We have been working on clean installations on Ubuntu system and we have come with a set of instructions similar to those you provide on the CentOS script.

Here are the instructions if they are of any help:

# Casebox on Ubuntu 14.04

Start with a clean install and make sure the software is up to date:
`$ sudo apt-get update`

## Install Apache 2.4
`$ sudo apt-get install apache2`
`$ sudo a2enmod rewrite`
`$ sudo a2enmod headers`
`$ sudo a2enmod ssl`

------------------------------------------------
For *developer* mode on local server
`$ echo "ServerName localhost" | sudo tee /etc/apache2/conf-available/fqdn.conf`
`$ sudo a2enconf fqdn`

------------------------------------------------
`sudo service apache2 restart`

## Install MySQL 5.x
* When configuring root password, the casebox install script had issues with special characters.  Avoid quotes and other characters to prevent conflicts:

`$ sudo apt-get install mysql-server php5-mysql`
`$ sudo mysql_install_db`
For security reasons, run:
`$ sudo mysql_secure_installation`

## Insatll PHP 5.x
`$ sudo apt-get install php5 libapache2-mod-php5 php5-mcrypt php5-mysqlnd`

## Install JAVA (1.7+)
`$ sudo apt-get install default-jdk`

## Install SOLR 5.2
- Navigate to: http://lucene.apache.org/solr/
- Click on Download
- Select a Mirror
- Download: **solr-5.X.X.tgz** (as of this writting solr-5.2.0.tgz)
- On the terminal cd to the donwload location

`$ tar xzf solr-5.2.0.tgz solr-5.2.0/bin/install_solr_service.sh --strip-components=2`
`$ sudo bash ./install_solr_service.sh solr-5.2.0.tgz`

Follow on-screen instructions and then confirm by running
`$ sudo service solr status`

## Install Imagemagick and imagick for php
`$ sudo apt-get install imagemagick`
`$ sudo apt-get install php5-imagick`
`$ sudo php5enmod imagick`
`$ sudo service apache2 restart`

## Clone and install the project
- cd to **/var/www/html** (default Apache 2.4 directory under Ubuntu)

`$ sudo apt-get install git`
`$ sudo git clone https://github.com/KETSE/casebox.git`
`$ sudo mkdir /var/www/html/casebox/logs`
`$ sudo mkdir /var/www/html/casebox/data`
`$ sudo touch /var/www/html/casebox/httpsdocs/config.ini`
`$ sudo chown -R www-data:www-data /var/www/html/casebox/`

------------------------------------------------
For *developer* mode on local server
`$ cd casebox`
`$ sudo git checkout devel`
`$ sudo chown -R www-data:www-data /var/www/html/casebox/`

------------------------------------------------

## Run the Casebox install.php
`$ sudo php bin/install.php`

__Important !__
- Default Apache owner on Ubuntu is **www-data**, not *apache*, be sure to override that default.
- We are configuring later on Casebox virtual host to be casebox.local and on port 80 non-https, so we sugest **http://casebox.local/** as the base URL.

## Configure Apache for Local Development non-SSL on port :80

- edit file /etc/hosts to include this line to configure your hostname as desired.  For our own example, we are using **casebox.local**

`127.0.0.1	casebox.local`
- Add this to the **/etc/apache2/sites-available/000-default.conf** file (changing to your own configuration options for names, ports, etc.).  We are overriding the default port:80 localhost, so, you may need to change or delete the default Apache virtual host.  You may also configure the casebox virtual host on a different port

```xml
<VirtualHost *:80>
    # change it to your devel/production domain
    ServerName casebox.local

    ServerAdmin admin@domain.com

    # Windows ------------------------------------------
    # DocumentRoot "c:/var/www/casebox/httpsdocs"
    # CustomLog c:/var/www/casebox/logs/ssl_access_log common
    # ErrorLog  "c:/var/www/casebox/logs/ssl_error_log"

    # Linux --------------------------------------------
    DocumentRoot "/var/www/html/casebox/httpsdocs"
    CustomLog /var/www/html/casebox/logs/ssl_access_log common
    ErrorLog  "/var/www/html/casebox/logs/ssl_error_log"

    # SSLEngine on
    # SSLVerifyClient none

    # provide your own SSL certificates or remove SSL support and use CaseBox via http
    # you may change the location of SSL certificates

    # Windows ------------------------------------------
    # SSLCertificateFile c:/var/www/casebox/install/httpd/ssl/casebox.crt
    # SSLCertificateKeyFile c:/var/www/casebox/install/httpd/ssl/casebox.key

    # Linux
    # SSLCertificateFile /var/www/html/casebox/install/httpd/ssl/casebox.crt
    # SSLCertificateKeyFile /var/www/html/casebox/install/httpd/ssl/casebox.key

    # SSLProtocol All -SSLv2 -SSLv3
    # SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:!RC4:HIGH:!MD5:!aNULL:!EDH


    # SSLHonorCipherOrder on
    # Add six earth month HSTS header for all users...
    Header add Strict-Transport-Security "max-age=15768000"

    # HTTP Security Headers
    Header add X-Content-Type-Options no-sniff
    Header add X-Download-Options noopen
    # Header add X-Frame-Options deny
    Header add X-XSS-Protection "1; mode=block"

    # Windows ------------------------------------------
    # <Directory c:/var/www/casebox/httpsdocs>
    # Linux
    <Directory /var/www/html/casebox/httpsdocs>
	<IfModule mod_php5.c>
	    php_admin_flag engine on
	    php_admin_flag safe_mode off

	    # Windows ------------------------------------------
	    # php_admin_value open_basedir "c:/var/www/casebox/;c:/windows/temp;"

	    # Linux --------------------------------------------
	    # php_admin_value open_basedir "/var/www/html/casebox/:/usr/lib64/libreoffice:/tmp"

	    php_admin_value max_execution_time 300
	    php_admin_value short_open_tag off

	    php_admin_value upload_max_filesize 200M
	    php_admin_value post_max_size 200M
	    php_admin_value max_file_uploads 20
	    php_admin_value memory_limit 200M

	    php_admin_value expose_php Off
	</IfModule>

	#SSLRequireSSL
	Options -Includes -ExecCGI
	AllowOverride All
    </Directory>
</VirtualHost>
```

`$ sudo service apache2 restart`

**Comment by smugderby** [comment]
This is very good. I'm running it now.. but for the apache service restart I needed to add sudo to the command.

**Comment by ajinkyagadewar** [comment]
I am getting Error "Error, invalid url." if I change AllowOverride ALL to AllowOverride None. If I run with default virtual host, I am getting error "Permission Denied."

Can you tell me what I am missing? 

PS: All other settings are exactly done as shown.

**Comment by smugderby** [comment]
I would suggest you use the Apache conf file present under casebox/install/httpd and make sure the settings there match your directories. Make sure if you're running under windows/linux the paths are written correctly and that the folders have the necessary permissions. More details about your OS and your own configuration file would be helpful.

**Comment by ajinkyagadewar** [comment]
I am using Ubuntu 14.04 and following is my config file.

PYTHON = python
prefix = cb
apache_user = www-data
db_host = localhost
db_port = 3306
su_db_user = root
db_user = root
db_pass = ajinkya
server_name = http://doc.buffersoftware.com/
solr_home = /var/solr/data/
solr_host = 127.0.0.1
solr_port = 8983
session.lifetime = 180
admin_email = ajinkya@Bufferts.com
sender_email = ajinkya@bufferts.com
backup_dir = /var/www/html/casebox/backup/

**Comment by ajinkyagadewar** [comment]
Below is my apache configuration:
<VirtualHost 128.199.83.250:80>
    # change it to your devel/production domain
    ServerName doc.buffersoftware.com

    ServerAdmin  support@casebox.org

    # Windows ------------------------------------------
    #DocumentRoot "c:/var/www/html/casebox/httpsdocs"
    #CustomLog c:/var/www/html/casebox/logs/ssl_access_log common
    #ErrorLog  "c:/var/www/html/casebox/logs/ssl_error_log"

    # Linux --------------------------------------------
     DocumentRoot "/var/www/html/casebox/httpsdocs"
     CustomLog /var/www/html/casebox/logs/ssl_access_log common
     ErrorLog  "/var/www/html/casebox/logs/ssl_error_log"

    #SSLEngine on
    #SSLVerifyClient none

    # provide your own SSL certificates or remove SSL support and use CaseBox via http
    # you may change the location of SSL certificates

    # Windows ------------------------------------------
    #SSLCertificateFile c:/var/www/html/casebox/install/httpd/ssl/casebox.crt
    #SSLCertificateKeyFile c:/var/www/html/casebox/install/httpd/ssl/casebox.key

    # Linux
    # SSLCertificateFile /etc/apache2/ssl/apache.crt
    # SSLCertificateKeyFile /etc/apache2/ssl/apache.key

    #SSLProtocol All -SSLv2 -SSLv3
    #SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:!RC4:HIGH:!MD5:!aNULL:!EDH


    #SSLHonorCipherOrder on
    # Add six earth month HSTS header for all users...
    Header add Strict-Transport-Security "max-age=15768000"

    # HTTP Security Headers
    Header add X-Content-Type-Options no-sniff
    Header add X-Download-Options noopen
    # Header add X-Frame-Options deny
    Header add X-XSS-Protection "1; mode=block"

    # Windows ------------------------------------------
    #<Directory c:/var/www/html/casebox/httpsdocs>
    # Linux
     <Directory /var/www/html/casebox/httpsdocs>
        <IfModule mod_php5.c>
            php_admin_flag engine on
            php_admin_flag safe_mode off

            # Windows ------------------------------------------
            #php_admin_value open_basedir "c:/var/www/html/casebox/;c:/windows/temp;"

            # Linux --------------------------------------------
          #   php_admin_value open_basedir "/var/www/html/casebox/:/usr/lib64/libreoffice:/tmp"

            php_admin_value max_execution_time 300
            php_admin_value short_open_tag off

            php_admin_value upload_max_filesize 200M
            php_admin_value post_max_size 200M
            php_admin_value max_file_uploads 20
            php_admin_value memory_limit 200M

            php_admin_value expose_php Off
        </IfModule>

     #   SSLRequireSSL
        Options -Includes -ExecCGI
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>

**Comment by ajinkyagadewar** [comment]
If I change AllowOverride None to ALL, I start getting Permission Denied error

**Comment by RafaPolit** [comment]
ajinkyagedewar,

The AllowOverride All is required for the mod_rewrite module, which is a requisite as per casebox instructions.

I believe the Permission Denied error is actually the expected behavior if you are just going to
`http://localhost`

Perhaps its a bit unclear in the instructions, but you need to go to
`http://localhost/coreName`

Where coreName is the actual name of the default core you configured on you installation script (or any other core you have created).

Hope this helps,
Best regards,
Rafa.

**Comment by ajinkyagadewar** [comment]
Thanks Rafa and SmugDerby. It worked. I was missing the basic configuration.

**Comment by oburlaca** [comment]
Thanks @RafaPolit for the guide, I've created a wiki page:
https://github.com/KETSE/casebox/wiki/How-to-install-Casebox-on-a-fresh-Ubuntu-14.04

closing issue

**Comment by lolziac** [comment]
Dear All,

I installed casebox on Ubuntu 14.04, but i'm encountering problems with file preview...Libreoffice and unoconv (I can't make it work...I guess I'm missing something).
Even though when I click on the file after I upload...it just shows the Edit window...I even can't download (see img)

![casebox](https://cloud.githubusercontent.com/assets/583004/8911711/7a05bfc6-348e-11e5-9dd3-8045ae79cb38.png)

If anybody who made it work on Ubuntu, please can you share the procedure with us.

I followed these two Install Procedures:
https://www.casebox.org/dev/install/
https://github.com/KETSE/casebox/issues/9
```
#uname -a
Linux casebox 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
=================================
CaseBox 1.9.498 (2015-07-27)
=================================
#dpkg -l | grep '^ii' | grep office
ii  libreoffice                           1:4.2.8-0ubuntu2                    amd64        office productivity suite (metapackage)
ii  libreoffice-avmedia-backend-gstreamer 1:4.2.8-0ubuntu2                    amd64        GStreamer backend for LibreOffice
ii  libreoffice-base                      1:4.2.8-0ubuntu2                    amd64        office productivity suite -- database
ii  libreoffice-base-core                 1:4.2.8-0ubuntu2                    amd64        office productivity suite -- shared library
ii  libreoffice-base-drivers              1:4.2.8-0ubuntu2                    amd64        Database connectvity drivers for LibreOffice
ii  libreoffice-calc                      1:4.2.8-0ubuntu2                    amd64        office productivity suite -- spreadsheet
ii  libreoffice-common                    1:4.2.8-0ubuntu2                    all          office productivity suite -- arch-independent files
ii  libreoffice-core                      1:4.2.8-0ubuntu2                    amd64        office productivity suite -- arch-dependent files
ii  libreoffice-draw                      1:4.2.8-0ubuntu2                    amd64        office productivity suite -- drawing
ii  libreoffice-gnome                     1:4.2.8-0ubuntu2                    amd64        office productivity suite -- GNOME integration
ii  libreoffice-gtk                       1:4.2.8-0ubuntu2                    amd64        office productivity suite -- GTK+ integration
ii  libreoffice-impress                   1:4.2.8-0ubuntu2                    amd64        office productivity suite -- presentation
ii  libreoffice-java-common               1:4.2.8-0ubuntu2                    all          office productivity suite -- arch-independent Java support files
ii  libreoffice-math                      1:4.2.8-0ubuntu2                    amd64        office productivity suite -- equation editor
ii  libreoffice-pdfimport                 1:4.2.8-0ubuntu2                    amd64        PDF Import component for LibreOffice
ii  libreoffice-report-builder-bin        1:4.2.8-0ubuntu2                    amd64        LibreOffice component for building database reports -- libraries
ii  libreoffice-sdbc-firebird             1:4.2.8-0ubuntu2                    amd64        Firebird SDBC driver for LibreOffice
ii  libreoffice-sdbc-hsqldb               1:4.2.8-0ubuntu2                    amd64        HSQLDB SDBC driver for LibreOffice
ii  libreoffice-style-galaxy              1:4.2.8-0ubuntu2                    all          office productivity suite -- Galaxy (Default) symbol style
ii  libreoffice-style-human               1:4.2.8-0ubuntu2                    all          office productivity suite -- Human symbol style
ii  libreoffice-writer                    1:4.2.8-0ubuntu2                    amd64        office productivity suite -- word processor
=================================
# python -V
Python 2.7.6
=================================
I remove the apt downloads and installed the deb from libreoffice site (again no luck)

dpkg -i LibreOffice_4.4.4.3_Linux_x86-64_deb/DEBS/*.deb
-rw-r--r-- 1 root root   2008824 Qer 24 01:04 libobasis4.4-base_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root  10507092 Qer 24 01:04 libobasis4.4-calc_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root 136166258 Qer 24 01:07 libobasis4.4-core_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root      4660 Qer 24 01:04 libobasis4.4-draw_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root     87694 Qer 24 01:04 libobasis4.4-en-us_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root     22902 Qer 24 01:03 libobasis4.4-en-us-base_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root     51346 Qer 24 01:04 libobasis4.4-en-us-calc_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root     16180 Qer 24 01:04 libobasis4.4-en-us-math_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    194172 Qer 24 01:03 libobasis4.4-en-us-res_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root      1090 Qer 24 01:05 libobasis4.4-en-us-writer_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    270886 Qer 24 01:04 libobasis4.4-extension-beanshell-script-provider_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    605852 Qer 24 01:04 libobasis4.4-extension-javascript-script-provider_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   2949840 Qer 24 01:08 libobasis4.4-extension-mediawiki-publisher_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   1018188 Qer 24 01:03 libobasis4.4-extension-nlpsolver_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    908318 Qer 24 01:08 libobasis4.4-extension-pdf-import_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   3450524 Qer 24 01:08 libobasis4.4-extension-report-builder_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root     47620 Qer 24 01:03 libobasis4.4-filter-data_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    515194 Qer 24 01:04 libobasis4.4-gnome-integration_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   3818420 Qer 24 01:03 libobasis4.4-graphicfilter_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root  10504290 Qer 24 01:04 libobasis4.4-images_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   1104496 Qer 24 01:04 libobasis4.4-impress_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    133450 Qer 24 01:04 libobasis4.4-kde-integration_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    119416 Qer 24 01:04 libobasis4.4-librelogo_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    527506 Qer 24 01:05 libobasis4.4-math_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    117018 Qer 24 01:04 libobasis4.4-ogltrans_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    173866 Qer 24 01:03 libobasis4.4-onlineupdate_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root  17929062 Qer 24 01:05 libobasis4.4-ooofonts_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root      1102 Qer 24 01:04 libobasis4.4-ooolinguistic_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   1574382 Qer 24 01:08 libobasis4.4-postgresql-sdbc_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root     11066 Qer 24 01:03 libobasis4.4-python-script-provider_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root  11129292 Qer 24 01:04 libobasis4.4-pyuno_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   5348880 Qer 24 01:04 libobasis4.4-writer_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    441506 Qer 24 01:03 libobasis4.4-xsltfilter_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root    457888 Qer 24 01:05 libreoffice4.4_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root       778 Qer 24 01:03 libreoffice4.4-base_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root       778 Qer 24 01:08 libreoffice4.4-calc_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   6459892 Qer 23 23:30 libreoffice4.4-debian-menus_4.4.4-3_all.deb
-rw-r--r-- 1 root root   6567716 Qer 24 01:08 libreoffice4.4-dict-en_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   1379002 Qer 24 01:04 libreoffice4.4-dict-es_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   2230466 Qer 24 01:04 libreoffice4.4-dict-fr_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root       778 Qer 24 01:07 libreoffice4.4-draw_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root      5992 Qer 24 01:04 libreoffice4.4-en-us_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root       788 Qer 24 01:04 libreoffice4.4-impress_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root       780 Qer 24 01:03 libreoffice4.4-math_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root   4023626 Qer 24 01:04 libreoffice4.4-ure_4.4.4.3-3_amd64.deb
-rw-r--r-- 1 root root       782 Qer 24 01:04 libreoffice4.4-writer_4.4.4.3-3_amd64.deb
```

**Comment by capuni** [comment]
I have followed the above step-by-step and I am getting the following "Error code: ssl_error_rx_record_too_long"

**Comment by capuni** [comment]
When trying the http I only get blank pages.

**Comment by lolziac** [comment]
Capuni,

Did you check your logs what they say.

It can be miss-configuration of apache conf or maybe some read access on your folder structure...or maybe also your DB connection !!

Path to logs folder...
/var/www/html/casebox/logs/

Regards,
lolziac

**Comment by pablocerdeira** [comment]
Hi all,

the install runs fine, but I cannot login: Wrong username or password

The last lines from the install.php:

-----
Do you want to create a basic default core [Y,n]: 
Core name:
cbma
OK
Registering core .. OK
Specify email address for root user:
**admin**
Specify root user password:
**senha**
Specify default language (ISO) (default "en"):

UI available languages (comma separated ISO list) (default "en"): 

Creating solr core ... OK
Reindex core [Y/n]: 
Reindexing core ... 
2015-12-17 12:38:34 Processing core cbma ... updating tree
optimizing
OK
Creating language files .. OK
Done.
Done
-----

After it, I can reach the login page at http://addr/cbma/login but when I try admin and senha the system returns Wrong username or password

I've tried a lot of different user/pass combinations (with email address, without etc).

Maybe some bug?

**Comment by smugderby** [comment]
Your credentials are root/senha not admin/senha

You were asked for your admin email not username.

On Thu, Dec 17, 2015 at 2:44 PM, Pablo Cerdeira <notifications@github.com>
wrote:

> Hi all,
>
> the install runs fine, but I cannot login: Wrong username or password
>
> The last lines from the install.php:
> ------------------------------
>
> Do you want to create a basic default core [Y,n]:
> Core name:
> cbma
> OK
> Registering core .. OK
> Specify email address for root user:
> *admin*
> Specify root user password:
> *senha*
> Specify default language (ISO) (default "en"):
>
> UI available languages (comma separated ISO list) (default "en"):
>
> Creating solr core ... OK
> Reindex core [Y/n]:
> Reindexing core ...
> 2015-12-17 12:38:34 Processing core cbma ... updating tree
> optimizing
> OK
> Creating language files .. OK
> Done.
> Done
>
> After it, I can reach the login page at http://addr/cbma/login but when I
> try admin and senha the system returns Wrong username or password
>
> I've tried a lot of different user/pass combinations (with email address,
> without etc).
>
> Maybe some bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KETSE/casebox/issues/9#issuecomment-165442819>.
>



-- 
Casebox Solutions
Consultant MENA Region
wael@huridocs.org

**Comment by pablocerdeira** [comment]
Thank you, smugderby. This worked. But I've tried email@email.com on config.php, without success. 

But now I'm in! Thank you again!

**Comment by BigWizzo** [comment]
I am trying to install casebox v1 using the instructions on this page. Everything ticks successful on my command line. If I go to http://mydomain/mycore I get a page not found error. And indeed, there are no core folders created in casebox/httpsdocs. I can see the cb_mycore database is created in mysql as well as the solr core. I do not know why the core folder is not created in httpsdocs. Please help me out if I am doing something wrong. I really need this project to work. 


Do you want to create a basic default core [Y,n]:
Core name:mycore
Core database exists. Would you like to backup it and overwrite with dump from current installation [Y/n]:
Backuping .. mysqldump: [Warning] Using a password on the command line interface can be insecure.
OK
mysql: [Warning] Using a password on the command line interface can be insecure.
OK
Registering core .. OK
Specify email address for root user:root
Specify root user password:root
Specify default language (ISO) (default "en"):
UI available languages (comma separated ISO list) (default "en"):
Solr core already exists, overwrite [Y/n]:
Unloading core mycore... OK
Creating solr core ... OK
Reindex core [Y/n]:
Reindexing core ...
2019-02-28 12:08:05 Processing core mycore ... updating tree
optimizing
OK
Creating language files .. OK
Done.
Done

**Comment by MotlatsoLaw** [comment]
anyone who can assist me with installing Casebox. I have tried so many hours . Please.

**Comment by seliwini** [comment]
@Majorlaw how did it go with ur installation.

**Comment by MajorLaw** [comment]
What installation are you referring to?

**Comment by seliwini** [comment]
Casebox setup

￼
